# -*- coding: utf-8 -*-
"""hw10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsN77WK6V64dUgMYxr_-cTPUHLkcsaxW
"""



import pickle
import os


def save_scores(scores):
    with open('score.bin', 'wb') as f:
        pickle.dump(scores, f)


def load_scores():
    if os.path.exists('score.bin'):
        with open('score.bin', "rb") as f:

            return pickle.load(f)
    else:
        return None


def input_scores():
    scores = []
    while True:
        score = int(input('#{}? '.format(len(scores) + 1)))

        if score == -1:
            break
        scores.append(score)

    return scores


def print_scores(scores):
    if scores:
        print('[점수 출력]')
        print('개인점수:', *scores)
        print('평균:', sum(scores) / len(scores))

    else:
        print("저장된 점수가 없습니다.")



scores = load_scores()

if scores:
    print('[파일 읽기]')
    print()
    print_scores(scores)

else:
    print('[점수 입력]')

if not scores:
    scores = input_scores()
    save_scores(scores)
    print()
    print_scores(scores)