# -*- coding: utf-8 -*-
"""hw4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MEzRps2ZTYi9GMKoRlmxwD3Qeq5k-aus
"""

def rep_char(c,n):
  print(c*n)

from ast import NodeVisitor
def draw_line_string():
  msg= input(' Input his/her name: ')

  msg1= f'Hello {msg},'
  msg2 = 'Welcome to Seoul.'

  nstr = len(msg1) if(len(msg1)>len(msg2))else len(msg2)

  rep_char('-',nstr+2)
  print (f' {msg1} ')
  print (f' {msg2} ')
  rep_char('-',nstr+2)

draw_line_string()