# -*- coding: utf-8 -*-
"""hw5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vy2pQiaddP1jimVnTD38IkL3_n6oy4YX
"""

def read_single_digit(sc):
  if sc == '1' :
    return '일'
  elif sc == '2':
    return '이'
  elif sc == '3':
    return '삼'
  elif sc == '4':
    return '사'
  elif sc == '5':
    return '오'
  elif sc == '6':
    return '육'
  elif sc == '7':
    return '칠'
  elif sc == '8':
    return '팔'
  elif sc == '9':
    return '구'
  elif sc == '0':
    return '영'


def read_number(tc):
  return read_single_digit(tc)


answk= input('세 자리 정수 입력:')
tric1=answk[0]
tric2=answk[1]
tric3=answk[2]



print(f'{read_number(tric1)} {read_number(tric2)} {read_number(tric3)}')