# -*- coding: utf-8 -*-
"""hw8(연습문제10.6).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1GpYk3QKS5LvBPy6ZjhJdry-6CO_Tp7
"""

def buy(a):
  while True:
    print('[구입]')
    name = input('상품명? ')
    if name == '':
      return False
    price = int(input('수량은? '))
    a[name] = price
    print(f'장바구니에 {name} {price}개가 담겼습니다.')
    print('')


def show(b):
  print('')
  print(f'>>> 장바구니 보기: {b}')

def find(c):
  print('')
  print('[검색]')
  ask= input('장바구니에서 확인하고자 하는 상품은? ')
  if ask in c:
    print(f'{ask}은(는) {c[ask]}개 담겨 있습니다.')
  else:
    print(f'장바구니에 {ask}은(는) 없습니다.')







shopping_bag={}
while True:
  if buy(shopping_bag) == False:
    break
show(shopping_bag)
find(shopping_bag)
